// Generated by CoffeeScript 1.4.0
(function() {

  GL.displayLyricsFor = function(artist, title) {
    var lyrics, request;
    if (title.match(/remaster/i)) {
      title = title.split(' - ')[0];
    }
    artist = artist.replace(' ', '_');
    title = title.replace(' ', '_');
    request = new XMLHttpRequest();
    request.open('GET', "http://lyrics.wikia.com/" + artist + ":" + title);
    lyrics = '(no lyrics found)';
    request.onreadystatechange = function() {
      var lyricsDocument;
      if (request.readyState === 4 && request.status === 200) {
        lyricsDocument = document.implementation.createHTMLDocument('lyrics');
        lyricsDocument.documentElement.innerHTML = request.responseText;
        lyrics = lyricsDocument.getElementsByClassName('lyricbox')[0].innerHTML.replace(/\n/g, '').replace(/<br>/g, '\n').replace(/<.+>/g, '').replace(/\n/g, '<br>');
      }
      return GL.elements.lyricsElement.innerHTML = lyrics;
    };
    return request.send();
  };

}).call(this);
