// Generated by CoffeeScript 1.4.0
(function() {

  GL.init = function() {
    GL.sp = getSpotifyApi(1);
    GL.models = GL.sp.require('sp://import/scripts/api/models');
    GL.player = GL.models.player;
    GL.elements = {};
    GL.elements.titleElement = document.getElementById('title');
    GL.elements.artistElement = document.getElementById('artist');
    return GL.elements.lyricsElement = document.getElementById('lyrics');
  };

}).call(this);
