// Generated by CoffeeScript 1.4.0
(function() {

  window.onload = function() {
    GL.init();
    GL.updateView();
    return GL.player.observe(GL.models.EVENT.CHANGE, function(event) {
      if (event.data.curtrack) {
        return GL.updateView();
      }
    });
  };

}).call(this);
