// Generated by CoffeeScript 1.4.0
(function() {

  GL.updateView = function() {
    var artist, title;
    if (GL.player.track) {
      artist = GL.player.track.artists[0].toString();
      title = GL.player.track.name;
      GL.elements.titleElement.innerHTML = title;
      GL.elements.artistElement.innerHTML = artist;
      return GL.displayLyricsFor(artist, title);
    }
  };

}).call(this);
