// Generated by CoffeeScript 1.4.0
(function() {

  GL.updateView = function() {
    if (GL.player.track) {
      GL.elements.titleElement.innerHTML = GL.player.track.name;
      return GL.elements.artistElement.innerHTML = GL.player.track.artists[0].toString();
    }
  };

}).call(this);
